"""add gravatar

Revision ID: 130acff431a
Revises: 35e18851de0
Create Date: 2016-11-18 19:23:34.280866

"""

# revision identifiers, used by Alembic.
revision = '130acff431a'
down_revision = '35e18851de0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
