"""bug fix

Revision ID: 137047e1f7c
Revises: 5a2fdc211e0
Create Date: 2016-11-19 13:58:10.328490

"""

# revision identifiers, used by Alembic.
revision = '137047e1f7c'
down_revision = '5a2fdc211e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
