"""bug fix

Revision ID: 1b5c5a885d3
Revises: 35d2f7a6c02
Create Date: 2016-11-17 17:28:22.417809

"""

# revision identifiers, used by Alembic.
revision = '1b5c5a885d3'
down_revision = '35d2f7a6c02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
