"""add gravatar

Revision ID: 210a412005f
Revises: 221573f862b
Create Date: 2016-11-18 19:14:56.742193

"""

# revision identifiers, used by Alembic.
revision = '210a412005f'
down_revision = '221573f862b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
