"""add gravatar

Revision ID: 221573f862b
Revises: 557c70925d2
Create Date: 2016-11-18 19:07:46.553600

"""

# revision identifiers, used by Alembic.
revision = '221573f862b'
down_revision = '557c70925d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
