"""bug fix

Revision ID: 2d6a35b94d6
Revises: 8df809cf27
Create Date: 2016-11-19 13:53:40.823477

"""

# revision identifiers, used by Alembic.
revision = '2d6a35b94d6'
down_revision = '8df809cf27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
