"""add confirmation token

Revision ID: 2f889a6187c
Revises: 36dd2eca7afa
Create Date: 2016-11-15 14:12:41.967237

"""

# revision identifiers, used by Alembic.
revision = '2f889a6187c'
down_revision = '36dd2eca7afa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
