"""add gravatar

Revision ID: 35e18851de0
Revises: 210a412005f
Create Date: 2016-11-18 19:17:41.018337

"""

# revision identifiers, used by Alembic.
revision = '35e18851de0'
down_revision = '210a412005f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
