"""bug fix

Revision ID: 557c70925d2
Revises: 1b5c5a885d3
Create Date: 2016-11-17 18:07:57.892459

"""

# revision identifiers, used by Alembic.
revision = '557c70925d2'
down_revision = '1b5c5a885d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
