"""bug fix

Revision ID: 5a2fdc211e0
Revises: 2d6a35b94d6
Create Date: 2016-11-19 13:54:37.869888

"""

# revision identifiers, used by Alembic.
revision = '5a2fdc211e0'
down_revision = '2d6a35b94d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
