"""bug fix

Revision ID: 8df809cf27
Revises: 3ec9ca4b928
Create Date: 2016-11-19 13:52:54.473582

"""

# revision identifiers, used by Alembic.
revision = '8df809cf27'
down_revision = '3ec9ca4b928'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
